Feature/jeongheekim level1 : 도메인 코드 생성
f-lab-edu/blackjack-game pull request #2
Opened 2023-06-18 10:19 UTC by ZhenxiKim

블랙잭 게임을 구성하는 도메인 클래스를 생성했습니다. 블랙잭 게임 구현을 위해 설계도는 해당 프로젝트에 img파일로 추가했습니다.
- Dealer : 딜러 객체
- Participant : 게임 참가자 객체
- Game : 게임 객체( 게임 규칙 및 진행 역할)
- Card : 카드 객체
- CardDeck : 게임 셋 진행을 위한 카드 셋 객체

2023-06-18 13:17 UTC, f-lab-maverick commented
@ZhenxiKim 베이스브랜치가 `master`브랜치로 되어있는것으로 보입니다. 개인 브런치 생성 후 베이스 브랜치 변경 부탁드려요~

2023-06-18 13:30 UTC, f-lab-maverick requested changes
첫 PR 확인하였습니다 👍
피드백 남기겠습니다.

1. PR을 생성하실 때에는 무엇을 구현했는지도 중요하지만, 왜 이렇게 구현했는지 의도를 설명해주시는것이 좋습니다. 개발한 내용은 코드를 보면 파악할 수 있지만 의도를 파악하기는 어렵기 때문입니다.

2. 설계 초안을 그려주신 부분은 아주 좋습니다. 앞으로도 이렇게 설계를 시도한 부분을 첨부해주세요~

2023-06-18 13:30 UTC, f-lab-maverick commented on src/Card.java
> +	private String shape;
1. `Card`에 `name` 이 필요할까요? name이라는 이름은 카드명이 들어갈 것으로 예상되는데 실제로는 카드의 숫자값이 들어갈 것으로 보입니다. 변수명, 상태명은 오해를 부를 수 있는 명명을 하면 실수가 일어날 가능성이 높기 때문에 이름을 지을 때 조금 더 명확한 이름을 고민해보는게 좋을 것으로 보입니다.
2. `shape`를 String 타입으로 선언한다면 오타나 예외에 대해서 처리하기 어렵지 않을까요? 이 부분은 어떻게 처리하는게 좋을까요?

2023-06-18 13:30 UTC, f-lab-maverick commented on src/Name.java
> +	K(10);
J, Q, K에 들어있는 value가 모두 같네요

2023-06-18 13:30 UTC, f-lab-maverick commented on src/Name.java
> +	K(10);
1. 이 부분은 Card의 Name이 아닌, 카드가 가진 값 속성이 아닐까요?
2. `ONE`의 경우 A로 표현할 수 있을것으로 보이네요~

2023-06-18 13:30 UTC, f-lab-maverick commented on src/Participant.java
> +}
1. `battingMoney`라는 타입은 int입니다. 만약, 협업중인 다른 개발자가 이 int타입 값을 보면 이게 원단위인지 달러단위인지 명시적으로 확인이 가능할까요?
2. Participant 는 User를 확장하고 있습니다. `battingMoney`라는 이름을 보니 게임 한판을 할 때 마다 배팅할 금액을 지정한 유저를 새로 생성하는 의도로 보입니다. 그렇다면, 참가를 할 때마다 `User`를 새로 생성하는것과 다르지 않을텐데 이렇게 설계하신 의도가 있으실까요?

2023-06-18 13:30 UTC, f-lab-maverick commented on src/Card.java
> +	private String shape;
Shape와 Name 타입을 생성했지만 적용되지 않았네요~

2023-06-18 15:06 UTC, ZhenxiKim commented
> @ZhenxiKim 베이스브랜치가 `master`브랜치로 되어있는것으로 보입니다. 개인 브런치 생성 후 베이스 브랜치 변경 부탁드려요~

pr을 master로 보냈었네요. 각자의 이름 브랜치로 다시 수정했습니다.

2023-06-19 08:39 UTC, ZhenxiKim commented on src/Card.java
> +	private String shape;
오타나 예외에 대해 방지하기 위해 Enum클래스를 선언하였는데 반영이 안되었었네요. 반영하겠습니다.

2023-06-19 09:36 UTC, ZhenxiKim commented on src/Name.java
> +	K(10);
제가 요구사항을 제대로 반영 못했네요! 
- One -> A로 변경
- 10 추가
- J,Q,K에 해당하는 점수는 10점 아닌가요?(https://m.blog.naver.com/haeunforever/221893584138)

2023-06-19 11:37 UTC, f-lab-maverick commented on src/Name.java
> +	K(10);
제가 JQK가 10점이라는점을 놓치고있었네요~

2023-06-19 14:16 UTC, ZhenxiKim commented on src/Participant.java
> +}
1. 화폐단위에 대해서는 변경이 일어나지 않으므로 enum클래스로 생성하고 Participant 속성으로 추가하였습니다.
2. 요구사항을 게임을 할때마다 참가자와 딜러를 새로 생성하고 배팅 금액을 셋팅한다고 생각한게 맞습니다.
User 부모클래스에는 딜러와 참가자가 공통적으로 가져야하는 속성인 보유한 카드 목록(List<Card> cardList)를 공통 필드로 뽑고 참가자만 가지는 속성인 배팅금액이 있어서 하위클래스 속성으로 뺐습니다.

2023-06-19 15:13 UTC, gutenLEE commented on src/User.java
> +	private List<Card> holdingCardList;
변수명이 의미가 명확해서 어떤 카드 리스트인지 파악이 쉽습니다!

2023-06-19 15:13 UTC, gutenLEE commented on src/Participant.java
> +}
Participant 클래스 속성에 화폐단위가 추가되었는데, 화폐단위는 battingMoney 와 관련된 속성이라 생각이 듭니다!

2023-06-19 15:13 UTC, gutenLEE commented on src/Participant.java
> +}
현실 세계에서 게임 유저는 배팅 머니를 소유하긴 하지만 
객체지향에서 게임 유저와 배팅 머니는 각각 독립된 객체로 보고 서로 협업을 하는 관계로 볼 수 있다고 생각합니다

2023-06-20 09:58 UTC, f-lab-maverick requested changes

2023-06-20 09:58 UTC, f-lab-maverick commented on src/Card.java
> +}
Card 객체의 `number`, `shape`가 객체개 생성된 이후 변경될 일이 있을까요?
변경될 여지가 없는 상태는 `final`키워드를 통해 상수로 변경해주신다면 추후 불변성이 유지되어 관리하기가 굉장히 편해집니다~
'불변객체'를 키워드로 한번 찾아보시겠어요?

2023-06-20 09:58 UTC, f-lab-maverick commented on src/Participant.java
> +}
`MoneyUnit`이 `Participant `에게 귀속되어있네요. 만약, 참가자가 다른 단위의 금액을 여러가지 가지고있다면 어떻게될까요?

객체지향에서 SRP를 유지하려면 참가자에게는 참가자 역할만 부여되어야 합니다.
금액과 단위를 관리하는건 참가자의 역할이 아닐 것으로 보이네요

2023-06-20 12:13 UTC, ZhenxiKim commented on src/Participant.java
> +}
저는 배팅금액을 참가자만 입력받는 요구사항에서 참가자가 가지는 속성이라고 생각했었습니다. 게임에서 가지는 단일 객체인 Money 클래스로 보는것이 맞겠네요

2023-06-21 12:01 UTC, f-lab-maverick approved these changes
고생하셨습니다. 머지하셔도 좋습니다~

2023-06-21 12:01 UTC, f-lab-maverick commented on src/Card.java
> +	}
👍

2023-06-21 12:01 UTC, f-lab-maverick commented on src/CardDeck.java
> +	}
생성자에서 이 메서드를 호출해도 되겠네요~

또는 반드시 인스턴스 생성시 처리해야 하는 로직이라면, Initializer Block을 사용해보는 방법도 있습니다. 아래 링크를 참고해보시겠어요?
https://www.baeldung.com/java-static-instance-initializer-blocks

2023-06-21 12:01 UTC, f-lab-maverick commented on src/Game.java
> +		cardDeck.settingCard();
`settingCard`라는걸 public 메소드로 노출시켜야 할까요? 이 메서드의 역할은 초기화인것으로 보이는데, 초기화 이후 다시 이 메서드를 호출할 일이 있을까요?

2023-06-21 12:01 UTC, f-lab-maverick commented on src/Number.java
> +public enum Number {
주석을 통해 카드의 번호라는 사실을 정리해주시는것도 좋지만, 이 Enum의 이름만 봐도 유추할 수 있는게 가장 Best 입니다. 주석이 없어도 이해할 수 있는 코드를 고민해보시는 것도 좋겠네요

2023-06-25 15:31 UTC, merged